language: python

python:
    - "2.7"
env:
    - DB=sqlite DJANGO=1.11
    - DB=postgresql DJANGO=1.11

install:
    - pip install Django==$DJANGO pisa reportlab html5lib BeautifulSoup psycopg2==2.4.1 xlwt==0.7.4 xhtml2pdf


before_script:
  - psql -c 'create database reports_creator;' -U postgres

script:
    - cd example
    - python manage.py test app --settings=test_project.settings_$DB --noinput

notifications:
  email:
    recipients:
      - joseph@bytcode.com
    on_success: always
    on_failure: always
